
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

# You will set env vars via the Netlify UI per-site and per-context.

# Example contexts (uncomment if you want to bake defaults here; recommended to use UI instead)
#[[context.production.environment]]
#  NODE_VERSION = "20"

#[[context.deploy-preview.environment]]
#  NODE_VERSION = "20"

[[redirects]]
  from = "/brand/:slug"
  to = "/brands/:slug"
  status = 301
  force = true

[[redirects]]
  from = "/product/:slug"
  to = "/products/:slug"
  status = 301
  force = true
